In [25]:
import os 
import pandas as pd 
import json
import numpy as np 

all_songs_path = "../data/songs-data-copy" 
artists_path = "./artists.json"
all_songs_files = [f for f in os.listdir(all_songs_path) if os.path.isfile(os.path.join(all_songs_path, f))]

songs_frame = pd.DataFrame(all_songs_files, columns=["song_name"]) 
songs_frame.head()

                                           song_name
0                                      001_Intro.mp3
1                                             1 .mp3
2  1 Addi Sunni (HD Video)  Karan Aujla  Tru-Skoo...
3  1 At Peace (Official Video) Karan Aujla _ Late...
4  1 Badmashi On Top  Masoom Sharma  Rahul Lamba ...

In [143]:
with open(artists_path, "r") as f:
    artists_obj = json.load(f)
flattened_artists = []
for category, artists in artists_obj.items():
    for artist in artists:
        flattened_artists.append({"category": category, "artist": artist})
artists_frame = pd.DataFrame(flattened_artists)
artists_frame[artists_frame["artist"].str.contains("m")]

    category         artist
3    punjabi       Cheema Y
13   punjabi   Prem Dhillon
38   punjabi  Parmish Verma
43   punjabi     Amrit Maan
53  haryanvi  Masoom Sharma
54  haryanvi  Vikram Sarkar
56  haryanvi  Rajkummar Rao
57  haryanvi   Amanraj Gill
58  haryanvi    Swara Verma
64  haryanvi    Hammy music

In [ ]:
def extract_name(x):
    for i in flattened_artists:
        if(i["artist"].split(" ")[0].lower() in x.lower() or i["artist"].split("-")[0].lower() in x.lower()):
            return i["artist"]
    
    return np.nan

songs_frame["artist"] = songs_frame["song_name"].apply(extract_name)

# First, create a mapping dictionary from artists_frame
artist_to_category = dict(zip(artists_frame['artist'], artists_frame['category']))

# Then, map the categories to songs_frame
songs_frame['category'] = songs_frame['artist'].map(artist_to_category)

stats = {"punjabi": 0, "haryanvi": 0, "unknown": 0, "total": 0}


for i in songs_frame["category"]:
    if(i == "punjabi"):
        stats["punjabi"] += 1
    elif(i == "haryanvi"):
        stats["haryanvi"] += 1
    else:
        stats["unknown"] += 1
    stats["total"] += 1
print(stats)

x = songs_frame["song_name"].str.contains("Banda", na=False)
songs_frame[x]

{'punjabi': 304, 'haryanvi': 0, 'unknown': 13, 'total': 317}

                                             song_name         artist category
5    1 Banda Bamb (OfficialAudio) Jordan Sandhu  Gu...  Jordan Sandhu  punjabi
135  Banda Bamb (OfficialAudio) Jordan Sandhu  Gur ...  Jordan Sandhu  punjabi
177  Dhanda Nyoliwala  Russian Bandana (Music Video...    Deep Kahlon  punjabi